[project]
name = "annotate-dafs"
version = "0.1.0"
description = "Annotate VCF files with derived allele frequencies."
readme = "README.md"
requires-python = ">=3.10"

dependencies = [
	"pysam",
	"vcfpy",
]

[project.scripts]
annotate-dafs = "annotate_dafs.cli:main"

[tool.setuptools.packages.find]
where = ["src"]